name:  microservice
description: |
   microservice image
version:  1.0.0
category:  WEB
maintainer:  liumiaocn
license:  Apache 2
projectURL: https://github.com/ liumiaocn/rancher-cattle-autocatalog
